### PR TITLE
Black

### PR DESCRIPTION
**Pull request by bluemellophone**
This PR adds black handling to IBEIS and also fixes the double quote character issue as raised by @Erotemic (https://github.com/WildbookOrg/wbia-tpl-pyflann/pull/3#issuecomment-638950441).

This update also changes the Black configuration slightly to support 90-character lines and other pre-commit requirements to check for security issues and other formatting problems.  Flake8 is the only pre-commit task that is failing.

The Black configuration is:
```
[tool.black]
line-length = 90
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
)/
'''
```

The pre-commit config is:
```
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.6
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: requirements-txt-fixer
      - id: check-toml
      # - id: check-json
      # - id: check-yaml
      # - id: check-ast
      # - id: check-executables-have-shebangs
      # - id: check-docstring-first
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
```

The current Flake8 ignores are:
```D100,D101,D102,D103,D105,D200,D205,D210,D400,D401,D403,E127,E201,E202,E203,E221,E222,E231,E241,E265,E271,E272,E301,E501,N802,N803,N805,N806,W503```

### CODE REVIEW

**Comment by bluemellophone** [comment]
As a minimal example of the single quote fix, see here: https://github.com/WildbookOrg/wildbook-ia/pull/27/files#diff-34a9ae8cc93aee04eb504f43badeb7a9.  This fill was processed by Black (with quotes turned off) and then cleaned by `double-quote-string-fixer`

**Comment by Erotemic** [comment]
Just to give a less self-righteous reason in support of single quotes for strings: it requires less typing. Pressing the `'` key by itself is much easier than pressing shift and `'` to achieve `"`. I also think it looks less cluttered. 

Obviously this is just an opinion and if you guys really like `"`, you can use them.

**Comment by mmulich** [comment]
@Erotemic, if it's less typing that is the issue, black as a pre-commit hook solves that. Basically, you can type `'` in your editor and black will change it to `"` on commit. I at first bulked at this as well, because I like single quotes for some things, but the consistency of it starts to wear on ya. 😸

**Comment by bluemellophone** [comment]
@mmulich @Erotemic I want to keep the single quote for the entire wbia-* codebase.  It is consistent with Python's use (https://github.com/psf/black/issues/373#issuecomment-435950436) and I would rather focus on the cleanliness of single quotes for easy readability.

The current configuration tells Black to ignore double quotes for non-docstrings and we use `double-quote-string-fixer` to intentionally convert double quotes to single quotes.

I've rebased this PR on `develop` after the latest vtool rename PR was merged in.  I've also added E231 to the ignore list for Flake8 since Black will resolve where this run is applied inconsistently for us.

**Comment by karenc** [comment]
Personally I also prefer single quotes.  I'm ok with skipping string normalization because ... well, in case the string has multiple single quotes, I think it's totally reasonable to use double quotes to quote the string.

**Pull request merged**
