### PR TITLE
Change base image to use cuda:10.0-cudnn7-devel-ubuntu18.04

### PR DESCRIPTION
**Pull request by karenc**
We were using `cuda:9.2-cudnn7-devel-ubuntu18.04`.

The latest version of cuda is 10.2 but the latest Tensorflow supports up
to CUDA 10.1 update 2:
https://github.com/tensorflow/tensorflow/issues/40227#issuecomment-653628234

Jason Parham: We are having to downgrade our tensorflow install and it needs 10.0

### CODE REVIEW

**Comment by bluemellophone** [comment]
Is this ready to be reviewed?

**Comment by karenc** [comment]
@bluemellophone I want to wait until the nightly builds are working before merging this PR.  I'm in the middle of fixing it.

**Comment by bluemellophone** [comment]
Karen, I've done some fixes in PyFlann and PyDarknet to fix building against CUDA 10.0.  Are you running into issues there?

**Comment by karenc** [comment]
@bluemellophone No, it looks like the nightly builds are passing now :tada:  It's ready to be merged. :+1:

**Pull request merged**
