### PR TITLE
Creating a runtime oriented container

### PR DESCRIPTION
**Pull request by mmulich**
This is a straight forward container that allows build workflows and dependency management tools to do the heavy lifting. We create the build dependencies as part of a build workflow and publish them to a package repository (i.e. PyPI). We then allow pip to pull in the dependencies. 

This removes the need to for build tools within the container, which is something we don't actually want laying around in a production worthy system.

---

Run using `docker build -t wildme/wildbook-ia .`

### CODE REVIEW

**Comment by bluemellophone** [comment]
@mmulich, what is the status of this PR?

**Comment by mmulich** [comment]
It'll work once all the packages are released. It's in limbo until we've tagged and released all-the-things to PyPI.

**Comment by karenc** [comment]
Made a small change to the entrypoint `ibeis.dev` -> `wbia.dev`:

```diff
diff --git a/Dockerfile b/Dockerfile
index fe6e3bf42..9375d7837 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -118,4 +118,4 @@ WORKDIR /data
 USER wbia
 
 # FIXME (4-Jun-12020) Use entrypoint script so that it'll be versatile and capable of running different ways.
-ENTRYPOINT ["python3", "-m ibeis.dev", "--dbdir", "/data/db", "--logdir", "/data/logs/", "--web", "--port", "5000", "--web-deterministic-ports", "--containerized", "--cpudark", "--production"]
+ENTRYPOINT ["python3", "-m wbia.dev", "--dbdir", "/data/db", "--logdir", "/data/logs/", "--web", "--port", "5000", "--web-deterministic-ports", "--containerized", "--cpudark", "--production"]
```

**Comment by karenc** [comment]
I think this is ready to be merged.  It's kind of similar to the set up we have in the github testing workflow.

**Pull request merged**
